# Port to run on
server:
  port: ${port:8081}

# Our log file path and name
logging:
  file: logs/erc20-rest-service.log

# Endpoint of an Ethereum or Quorum node we wish to use.
# To use IPC simply provide a file path to the socket, such as /path/to/geth.ipc
nodeEndpoint: http://localhost:22000

# The Ethereum or Quorum address we wish to use when transacting.
# Note - this address must be already unlocked in the client
fromAddress: "0xed9d02e382b34818e88b88a309c7fe71e65f419d"
